import type { WalletProvider } from "@/lib/types";

declare global { interface Window { freighterApi?: { isConnected: () => Promise<boolean>; getPublicKey: () => Promise<string>; signTransaction: (xdr: string, opts?: unknown) => Promise<string> }; xBull?: { connect: () => Promise<{ publicKey: string }>; sign: (xdr: string) => Promise<string> }; albedo?: { publicKey: (opts?: unknown) => Promise<{ pubkey: string }>; tx: (opts: { xdr: string; network: string }) => Promise<{ signed_envelope_xdr: string }> }; } }
export interface WalletSession { provider: WalletProvider; publicKey: string; connectedAt: string; }
export interface WalletConnector { id: WalletProvider; name: string; detect(): boolean; connect(): Promise<WalletSession>; sign(xdr: string): Promise<string>; }

const session = (provider: WalletProvider, publicKey: string): WalletSession => ({ provider, publicKey, connectedAt: new Date().toISOString() });
export const freighterConnector: WalletConnector = { id: "freighter", name: "Freighter", detect: () => typeof window !== "undefined" && Boolean(window.freighterApi), async connect() { if (!window.freighterApi) throw new Error("Freighter extension not found"); return session("freighter", await window.freighterApi.getPublicKey()); }, async sign(xdr) { if (!window.freighterApi) throw new Error("Freighter extension not found"); return window.freighterApi.signTransaction(xdr, { networkPassphrase: "Test SDF Network ; September 2015" }); } };
export const xbullConnector: WalletConnector = { id: "xbull", name: "xBull", detect: () => typeof window !== "undefined" && Boolean(window.xBull), async connect() { if (!window.xBull) throw new Error("xBull wallet not found"); const res = await window.xBull.connect(); return session("xbull", res.publicKey); }, async sign(xdr) { if (!window.xBull) throw new Error("xBull wallet not found"); return window.xBull.sign(xdr); } };
export const albedoConnector: WalletConnector = { id: "albedo", name: "Albedo", detect: () => typeof window !== "undefined" && Boolean(window.albedo), async connect() { if (!window.albedo) throw new Error("Albedo wallet not found"); const res = await window.albedo.publicKey({ require_existing: true }); return session("albedo", res.pubkey); }, async sign(xdr) { if (!window.albedo) throw new Error("Albedo wallet not found"); const res = await window.albedo.tx({ xdr, network: "testnet" }); return res.signed_envelope_xdr; } };
export const connectors = [freighterConnector, xbullConnector, albedoConnector];
