"use client";
import { useEffect, useState } from "react";
import { Badge, Button, Card } from "@/components/ui";
import { AppShell } from "@/components/shared/app-shell";
import { SkeletonCard } from "@/components/states/skeleton";
import { DonateButton } from "@/components/actions/donate-button";
import { getScholarship } from "@/lib/services/scholarship-service";
import type { Scholarship } from "@/lib/types";
export default function ScholarshipDetail({ params }: { params: { id: string } }) { const [s,setScholarship]=useState<Scholarship|null>(); const [error,setError]=useState<string>(); useEffect(()=>{getScholarship(params.id).then(setScholarship).catch((e)=>setError(e.message));},[params.id]); if(error) return <AppShell title="Scholarship unavailable" subtitle="Firestore returned an error."><p className="text-red-300">{error}</p></AppShell>; if(s===undefined) return <AppShell title="Loading scholarship" subtitle="Fetching live campaign metadata from Firestore."><SkeletonCard/></AppShell>; if(s===null) return <AppShell title="Scholarship not found" subtitle="The campaign may have been archived."><Button>Back to scholarships</Button></AppShell>; const pct=Math.round((s.raised/s.goal)*100); return <AppShell title={s.title} subtitle={s.description}><div className="grid gap-6 lg:grid-cols-[1.4fr_.8fr]"><Card><div className="flex flex-wrap gap-3"><Badge>{s.category}</Badge><Badge>{s.country}</Badge><Badge>{s.status}</Badge></div><h2 className="mt-6 text-2xl font-bold">Milestone escrow schedule</h2><div className="mt-5 space-y-3">{s.milestones.map((m,index)=><div key={m.id} className="rounded-2xl bg-white/[.06] p-4"><div className="flex items-center justify-between"><div><p className="font-semibold">{m.title}</p><p className="text-sm text-slate-400">{m.verifier} • due {m.dueDate}</p></div><Badge>{m.status}</Badge></div><p className="mt-2 text-sm text-mint">{m.amount} XLM • milestone #{index+1}</p></div>)}</div></Card><Card><p className="text-sm text-slate-400">Escrow contract</p><p className="mt-2 font-mono text-sm">{s.escrowContract}</p><div className="mt-6 h-3 rounded-full bg-white/10"><div className="h-full rounded-full bg-gradient-to-r from-aqua to-mint" style={{width:`${pct}%`}}/></div><p className="mt-3 text-slate-300">{s.raised} / {s.goal} XLM funded</p><div className="mt-6"><DonateButton scholarshipId={s.id} numericId={Number(s.id.replace(/\D/g,"")) || 1} amount={25}/></div></Card></div></AppShell>; }
